mysql-config:
  host: localhost
  user: root
  password: '123456'
  database: heima-movie

table-name: tb_user

field-mapping:
  bigint: Long
  int: Integer
  varchar: String
  datetime: LocalDateTime
  text: String
  decimal: Double
  tinyint: Integer

project-path: C:/Users/admin/IdeaProjects/crud-quickstart
# resultful风格
resultful: CommonResult

# null或者~为空值
template:
  Model:
    module: null
    package: cn.wnhyang.generator.entity
  Mapper:
    module: null
    package: cn.wnhyang.generator.mapper
  Service:
    module: null
    package: cn.wnhyang.generator.service
  ServiceImpl:
    module: null
    package: cn.wnhyang.generator.service.impl
  Controller:
    module: null
    package: cn.wnhyang.generator.controller
  QueryVo:
    module: null
    package: cn.wnhyang.generator.vo
  Vo:
    module: null
    package: cn.wnhyang.generator.vo
  CreateVo:
    module: null
    package: cn.wnhyang.generator.vo.create
  UpdateVo:
    module: null
    package: cn.wnhyang.generator.vo.update